config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: :edit
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  validates :name, presence: true, length:
    {maximum: Settings.maximum.name_max}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length:
    {maximum: Settings.maximum.email_max}, format:
    {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length:
    {minimum: Settings.minimum.pass_min},
    allow_nil: true
  has_secure_password
  before_save :downcase_email

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def activate
    update_columns activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by email: params[:email]
    if user && !user.activated? &&
       user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = t("account_activated")
      redirect_to user
    else
      flash[:danger] = t("account_invalid")
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      if user.activated?
        log_in user
        params[:session][:remember_me] == "1" ? remember(user) : forget(user)
        redirect_back_or user
      else
        flash[:warning] = t("require_check_email")
        redirect_to root_url
      end
    else
      flash.now[:danger] = t("login_fail")
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.page(params[:page]).per Settings.per_page
  end

  def show
    redirect_to(root_url) unless @user
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t("page_edit")
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t("del_user")
    else
      flash[:danger] = t("error")
    end
    redirect_to users_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "require_check_email"
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t("require_login")
    redirect_to login_url
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to root_url unless current_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t("something")
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "page_title"
    base_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user? user
    user == current_user
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated? :remember, cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.avatar_size}
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "the" %><%= link_to t("link_rails_rutorial"), "http://www.railstutorial.org/" %>
    <%= t "by" %><%= link_to t("michael"), "http://www.michaelhartl.com/" %>
  </small>

  <nav>
    <ul>
      <li><%= link_to t("title_about"), about_path %></li>
      <li><%= link_to t("title_contact"), contact_path %></li>
      <li><%= link_to t("static_pages.home.new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div>
    <%= link_to t("lang_english"), locale: "en" %>
    <%= link_to t("lang_vietnam"), locale: "vi" %>
  </div>
</header>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("title_app"), "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("title_home"), root_path %></li>
        <li><%= link_to t("title_about"), about_path %></li>
        <li><%= link_to t("title_contact"), contact_path %></li>
        <li><%= link_to t("title_help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("navbar_users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class:"dropdown-toggle", data: {toggle:"dropdown"} do %>
            <%= t "account"%> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("setting"),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("page_logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("page_login"), login_path %></li>
        <% end %>
        <li><%= link_to t("lang_english"), locale: "en" %></li>
        <li><%= link_to t("lang_vietnam"), locale: "vi" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= t "inform_error" %>
      <%= pluralize(@user.errors.count, t("error")) %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title%>
<body>
  <h1><%= t ".title" %></h1>
  <%= link_to t ".link_to_home" %><%= t ".link_name" %>
</body>

app/views/static_pages/contact.html.erb
<% provide :title %>
<body>
  <h1><%= t ".title" %></h1>
  <p>
    <%= link_to t ".link_contact" %><%= t ".link_name" %>
  </p>
</body>

app/views/static_pages/help.html.erb
<% provide :title %>
<body>
  <h1><%= t ".title" %></h1>
  <p>
    <%= link_to t ".link_to_help" %><%= t ".link_name" %><br>
  </p>
</body>

app/views/static_pages/home.html.erb
<% provide :title%>
<body>
  <div class="center jumbotron">
    <h1><%= t ".title" %></h1>
    <p>
      <%= link_to t(".link_to_home")%><%= t ".link_name" %>
    </p>
    <%= link_to t(".link_help"), help_path %> |
    <%= link_to t(".link_about"), about_path %> |
    <%= link_to t(".link_contact"), contact_path %><br>
    <%= link_to t("signup"), signup_path , class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("kitten.jpg", alt: "Kitten Image"), "http://rubyonrails.org/" %><br>
  <%= link_to image_tag("rails.png", alt: "Rails logo"), "http://rubyonrails.org/" %><br>
</body>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user%>

  <%= f.label :name, t("users.new.name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t("users.new.email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t("users.new.password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("users.new.password_confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.size_img %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to t("users.edit.del"), user, method: :delete, data: { confirm: t("question_before_del_user") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("page_edit") %>
<% provide :button_text, t("btn_update_account") %>
<h1><%= t "page_edit" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("change"), "http://gravatar.com/emails", target:"_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("all_user") %>
<h1><%= t "all_user" %></h1>

<ul class="users">
  <%= render @users %>
</ul>

<%= paginate @users, theme: "twitter-bootstrap-3" %>

app/views/users/login.html.erb
<% provide title: t(".login") %>
<h1><%= t ".title_login" %></h1>
<p><%= t ".detail" %></p>

app/views/users/new.html.erb
<% provide :title, t("page_signup") %>
<% provide :button_text, t("btn_create_account") %>
<h1><%= t "page_signup" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide :title, @user.name %>
<div class="row">
  <aside class="col-m-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>